export const MESSAGE_STATUS = {
  RECEIVED: 1,
  SENT: 2,
  REQUESTING: 3,
  FAILED: 4
};

export const CONVERSATION_TYPE = {
  SMS: 'SMS',
  MMS: 'MMS'
};

export const EVENTS = {
  INIT: 'INIT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  USER_CHANGED: 'USER_CHANGED',
  CONVERSATIONS_CHANGED: 'CONVERSATIONS_CHANGED',
  CONVERSATION_SELECTED: 'CONVERSATION_SELECTED',
  CONTACTS_CHANGED: 'CONTACTS_CHANGED',
  MESSAGES_CHANGED: 'MESSAGES_CHANGED',
  PHONE_STATUS_CHANGED: 'PHONE_STATUS_CHANGED',
  SEND_MESSAGE: 'SEND_MESSAGE',
  REQUEST_MMS_UPLOAD: 'REQUEST_MMS_UPLOAD'
};
